language: java

# Skip "install" stage:
install: true

# Use container-based infrastructure:
sudo: false

# Keep Maven local repository between builds:
cache:
  directories:
    - '$HOME/.m2/repository'

jdk:
  - openjdk7
  - openjdk8
  - openjdk10
  - openjdk11

script:
  - mvn clean install
